
CREATE PROCEDURE sp_ExisteCedulaVendedor
	@Cedula VARCHAR(50)
AS
BEGIN
	SET NOCOUNT ON;

  SELECT CASE WHEN EXISTS (
      SELECT 1 FROM Vendedores WHERE Cedula = @Cedula
  ) THEN 1 ELSE 0 END AS Existe;
END
GO
